#include <gfx/Api.h>
#include <emscripten/bind.h>

using namespace emscripten;

EMSCRIPTEN_BINDINGS(mud_gfx)
{
    
    // Enums
    enum_<mud::AnimationTarget>("mud::AnimationTarget")
        .value("Position", mud::AnimationTarget::Position)
        .value("Rotation", mud::AnimationTarget::Rotation)
        .value("Scale", mud::AnimationTarget::Scale)
        ;
    enum_<mud::BackgroundMode>("mud::BackgroundMode")
        .value("None", mud::BackgroundMode::None)
        .value("Panorama", mud::BackgroundMode::Panorama)
        .value("Radiance", mud::BackgroundMode::Radiance)
        .value("Custom", mud::BackgroundMode::Custom)
        ;
    enum_<mud::BlendMode>("mud::BlendMode")
        .value("Mix", mud::BlendMode::Mix)
        .value("Add", mud::BlendMode::Add)
        .value("Sub", mud::BlendMode::Sub)
        .value("Mul", mud::BlendMode::Mul)
        .value("Normal", mud::BlendMode::Normal)
        .value("Alpha", mud::BlendMode::Alpha)
        ;
    enum_<mud::CullMode>("mud::CullMode")
        .value("None", mud::CullMode::None)
        .value("Front", mud::CullMode::Front)
        .value("Back", mud::CullMode::Back)
        ;
    enum_<mud::DepthDraw>("mud::DepthDraw")
        .value("Enabled", mud::DepthDraw::Enabled)
        .value("Disabled", mud::DepthDraw::Disabled)
        ;
    enum_<mud::DepthTest>("mud::DepthTest")
        .value("Enabled", mud::DepthTest::Enabled)
        .value("Disabled", mud::DepthTest::Disabled)
        ;
    enum_<mud::EmitterFlow>("mud::EmitterFlow")
        .value("Outward", mud::EmitterFlow::Outward)
        .value("Absolute", mud::EmitterFlow::Absolute)
        ;
    enum_<mud::Interpolation>("mud::Interpolation")
        .value("Nearest", mud::Interpolation::Nearest)
        .value("Linear", mud::Interpolation::Linear)
        .value("Cubic", mud::Interpolation::Cubic)
        ;
    enum_<mud::IsometricAngle>("mud::IsometricAngle")
        .value("NORTH", mud::NORTH)
        .value("SOUTH", mud::SOUTH)
        .value("EAST", mud::EAST)
        .value("WEST", mud::WEST)
        ;
    enum_<mud::ItemShadow>("mud::ItemShadow")
        .value("Default", mud::ItemShadow::Default)
        .value("DoubleSided", mud::ItemShadow::DoubleSided)
        ;
    enum_<mud::LightType>("mud::LightType")
        .value("Direct", mud::LightType::Direct)
        .value("Point", mud::LightType::Point)
        .value("Spot", mud::LightType::Spot)
        .value("Count", mud::LightType::Count)
        ;
    enum_<mud::Lighting>("mud::Lighting")
        .value("None", mud::Lighting::None)
        .value("Clustered", mud::Lighting::Clustered)
        .value("Deferred", mud::Lighting::Deferred)
        .value("VoxelGI", mud::Lighting::VoxelGI)
        ;
    enum_<mud::MSAA>("mud::MSAA")
        .value("Disabled", mud::MSAA::Disabled)
        .value("X2", mud::MSAA::X2)
        .value("X4", mud::MSAA::X4)
        .value("X8", mud::MSAA::X8)
        .value("X16", mud::MSAA::X16)
        ;
    enum_<mud::MaterialFlag>("mud::MaterialFlag")
        .value("TriplanarUV1", mud::MaterialFlag::TriplanarUV1)
        .value("TriplanarUV2", mud::MaterialFlag::TriplanarUV2)
        .value("Count", mud::MaterialFlag::Count)
        ;
    enum_<mud::ModelFormat>("mud::ModelFormat")
        .value("obj", mud::ModelFormat::obj)
        .value("gltf", mud::ModelFormat::gltf)
        .value("Count", mud::ModelFormat::Count)
        ;
    enum_<mud::Month>("mud::Month")
        .value("January", mud::Month::January)
        .value("February", mud::Month::February)
        .value("March", mud::Month::March)
        .value("April", mud::Month::April)
        .value("May", mud::Month::May)
        .value("June", mud::Month::June)
        .value("July", mud::Month::July)
        .value("August", mud::Month::August)
        .value("September", mud::Month::September)
        .value("October", mud::Month::October)
        .value("November", mud::Month::November)
        .value("December", mud::Month::December)
        ;
    enum_<mud::PbrDiffuseMode>("mud::PbrDiffuseMode")
        .value("Lambert", mud::PbrDiffuseMode::Lambert)
        .value("LambertHalf", mud::PbrDiffuseMode::LambertHalf)
        .value("OrenNayar", mud::PbrDiffuseMode::OrenNayar)
        .value("Burley", mud::PbrDiffuseMode::Burley)
        .value("Toon", mud::PbrDiffuseMode::Toon)
        ;
    enum_<mud::PbrSpecularMode>("mud::PbrSpecularMode")
        .value("SchlickGGX", mud::PbrSpecularMode::SchlickGGX)
        .value("Blinn", mud::PbrSpecularMode::Blinn)
        .value("Phong", mud::PbrSpecularMode::Phong)
        .value("Toon", mud::PbrSpecularMode::Toon)
        .value("Disabled", mud::PbrSpecularMode::Disabled)
        ;
    enum_<mud::ShaderType>("mud::ShaderType")
        .value("Compute", mud::ShaderType::Compute)
        .value("Fragment", mud::ShaderType::Fragment)
        .value("Geometry", mud::ShaderType::Geometry)
        .value("Vertex", mud::ShaderType::Vertex)
        .value("Count", mud::ShaderType::Count)
        ;
    enum_<mud::Shading>("mud::Shading")
        .value("Wireframe", mud::Shading::Wireframe)
        .value("Unshaded", mud::Shading::Unshaded)
        .value("Shaded", mud::Shading::Shaded)
        .value("Volume", mud::Shading::Volume)
        .value("Voxels", mud::Shading::Voxels)
        .value("Lightmap", mud::Shading::Lightmap)
        .value("Clear", mud::Shading::Clear)
        .value("Count", mud::Shading::Count)
        ;
    enum_<mud::ShadowFlags>("mud::ShadowFlags")
        .value("CSM_Stabilize", mud::CSM_Stabilize)
        .value("CSM_Optimize", mud::CSM_Optimize)
        .value("CSM_BlendSplits", mud::CSM_BlendSplits)
        ;
    enum_<mud::TextureChannel>("mud::TextureChannel")
        .value("Red", mud::TextureChannel::Red)
        .value("Green", mud::TextureChannel::Green)
        .value("Blue", mud::TextureChannel::Blue)
        .value("Alpha", mud::TextureChannel::Alpha)
        .value("All", mud::TextureChannel::All)
        ;
    enum_<mud::TextureHint>("mud::TextureHint")
        .value("Black", mud::TextureHint::Black)
        .value("White", mud::TextureHint::White)
        .value("Normal", mud::TextureHint::Normal)
        ;
    enum_<mud::TextureSampler>("mud::TextureSampler")
        .value("Source0", mud::TextureSampler::Source0)
        .value("Source1", mud::TextureSampler::Source1)
        .value("Source2", mud::TextureSampler::Source2)
        .value("Source3", mud::TextureSampler::Source3)
        .value("SourceDepth", mud::TextureSampler::SourceDepth)
        .value("Color", mud::TextureSampler::Color)
        .value("Albedo", mud::TextureSampler::Albedo)
        .value("Metallic", mud::TextureSampler::Metallic)
        .value("Roughness", mud::TextureSampler::Roughness)
        .value("Emissive", mud::TextureSampler::Emissive)
        .value("Normal", mud::TextureSampler::Normal)
        .value("AO", mud::TextureSampler::AO)
        .value("Depth", mud::TextureSampler::Depth)
        .value("Skeleton", mud::TextureSampler::Skeleton)
        .value("ShadowCSM", mud::TextureSampler::ShadowCSM)
        .value("ShadowAtlas", mud::TextureSampler::ShadowAtlas)
        .value("Radiance", mud::TextureSampler::Radiance)
        .value("ReflectionProbe", mud::TextureSampler::ReflectionProbe)
        .value("GIProbe", mud::TextureSampler::GIProbe)
        .value("Lights", mud::TextureSampler::Lights)
        .value("Clusters", mud::TextureSampler::Clusters)
        .value("LightRecords", mud::TextureSampler::LightRecords)
        .value("Lightmap", mud::TextureSampler::Lightmap)
        ;
    
    // Sequences
    
    // Arrays
    
    // Structs
    value_object<mud::AnimatedTrack>("AnimatedTrack")
        ;
    value_object<mud::AnimationPlay>("AnimationPlay")
        .field("animation", &mud::AnimationPlay::m_animation)
        .field("loop", &mud::AnimationPlay::m_loop)
        .field("speed", &mud::AnimationPlay::m_speed)
        .field("transient", &mud::AnimationPlay::m_transient)
        .field("fadeout", &mud::AnimationPlay::m_fadeout)
        .field("fadeout_left", &mud::AnimationPlay::m_fadeout_left)
        .field("cursor", &mud::AnimationPlay::m_cursor)
        .field("ended", &mud::AnimationPlay::m_ended)
        ;
    value_object<mud::Background>("Background")
        .field("mode", &mud::Background::m_mode)
        .field("colour", &mud::Background::m_colour)
        .field("custoprogram", &mud::Background::m_custom_program)
        ;
    value_object<mud::BaseMaterialBlock>("BaseMaterialBlock")
        .field("blend_mode", &mud::BaseMaterialBlock::m_blend_mode)
        .field("cull_mode", &mud::BaseMaterialBlock::m_cull_mode)
        .field("depth_draw_mode", &mud::BaseMaterialBlock::m_depth_draw_mode)
        .field("depth_test", &mud::BaseMaterialBlock::m_depth_test)
        .field("uv0_scale", &mud::BaseMaterialBlock::m_uv0_scale)
        .field("uv0_offset", &mud::BaseMaterialBlock::m_uv0_offset)
        .field("uv1_scale", &mud::BaseMaterialBlock::m_uv1_scale)
        .field("uv1_offset", &mud::BaseMaterialBlock::m_uv1_offset)
        .field("is_alpha", &mud::BaseMaterialBlock::m_is_alpha)
        .field("screen_filter", &mud::BaseMaterialBlock::m_screen_filter)
        ;
    value_object<mud::Bone>("Bone")
        .field("position", &mud::Bone::m_position)
        .field("rotation", &mud::Bone::m_rotation)
        .field("scale", &mud::Bone::m_scale)
        ;
    value_object<mud::DepthParams>("DepthParams")
        ;
    value_object<mud::Environment>("Environment")
        .field("background", &mud::Environment::m_background)
        .field("radiance", &mud::Environment::m_radiance)
        .field("sun", &mud::Environment::m_sun)
        .field("fog", &mud::Environment::m_fog)
        ;
    value_object<mud::Fog>("Fog")
        .field("enabled", &mud::Fog::m_enabled)
        .field("density", &mud::Fog::m_density)
        .field("colour", &mud::Fog::m_colour)
        .field("depth", &mud::Fog::m_depth)
        .field("depth_begin", &mud::Fog::m_depth_begin)
        .field("depth_curve", &mud::Fog::m_depth_curve)
        .field("height", &mud::Fog::m_height)
        .field("height_min", &mud::Fog::m_height_min)
        .field("height_max", &mud::Fog::m_height_max)
        .field("height_curve", &mud::Fog::m_height_curve)
        .field("transmit", &mud::Fog::m_transmit)
        .field("transmit_curve", &mud::Fog::m_transmit_curve)
        ;
    value_object<mud::FresnelMaterialBlock>("FresnelMaterialBlock")
        .field("enabled", &mud::FresnelMaterialBlock::m_enabled)
        .field("value", &mud::FresnelMaterialBlock::m_value)
        .field("fresnel_scale", &mud::FresnelMaterialBlock::m_fresnel_scale)
        .field("fresnel_bias", &mud::FresnelMaterialBlock::m_fresnel_bias)
        .field("fresnel_power", &mud::FresnelMaterialBlock::m_fresnel_power)
        ;
    value_object<mud::FrustumSlice>("FrustumSlice")
        ;
    value_object<mud::ImportConfig>("ImportConfig")
        .field("format", &mud::ImportConfig::m_format)
        .field("position", &mud::ImportConfig::m_position)
        .field("rotation", &mud::ImportConfig::m_rotation)
        .field("scale", &mud::ImportConfig::m_scale)
        .field("transform", &mud::ImportConfig::m_transform)
        .field("exclude_elements", &mud::ImportConfig::m_exclude_elements)
        .field("exclude_materials", &mud::ImportConfig::m_exclude_materials)
        .field("include_elements", &mud::ImportConfig::m_include_elements)
        .field("include_materials", &mud::ImportConfig::m_include_materials)
        .field("suffix", &mud::ImportConfig::m_suffix)
        .field("force_reimport", &mud::ImportConfig::m_force_reimport)
        .field("cache_geometry", &mud::ImportConfig::m_cache_geometry)
        .field("optimize_geometry", &mud::ImportConfig::m_optimize_geometry)
        .field("flags", &mud::ImportConfig::m_flags)
        ;
    value_object<mud::Joint>("Joint")
        ;
    value_object<mud::MaterialParam<float>>("MaterialParam<float>")
        .field("value", &mud::MaterialParam<float>::m_value)
        .field("texture", &mud::MaterialParam<float>::m_texture)
        .field("channel", &mud::MaterialParam<float>::m_channel)
        ;
    value_object<mud::MaterialParam<mud::Colour>>("MaterialParam<mud::Colour>")
        .field("value", &mud::MaterialParam<mud::Colour>::m_value)
        .field("texture", &mud::MaterialParam<mud::Colour>::m_texture)
        .field("channel", &mud::MaterialParam<mud::Colour>::m_channel)
        ;
    value_object<mud::ModelItem>("ModelItem")
        .field("index", &mud::ModelItem::m_index)
        .field("mesh", &mud::ModelItem::m_mesh)
        .field("has_transform", &mud::ModelItem::m_has_transform)
        .field("transform", &mud::ModelItem::m_transform)
        .field("skin", &mud::ModelItem::m_skin)
        .field("colour", &mud::ModelItem::m_colour)
        .field("material", &mud::ModelItem::m_material)
        ;
    value_object<mud::ParticleGenerator>("ParticleGenerator")
        .field("name", &mud::ParticleGenerator::m_name)
        .field("duration", &mud::ParticleGenerator::m_duration)
        .field("start_time", &mud::ParticleGenerator::m_start_time)
        .field("loop", &mud::ParticleGenerator::m_loop)
        .field("shape", &mud::ParticleGenerator::m_shape)
        .field("flow", &mud::ParticleGenerator::m_flow)
        .field("billboard", &mud::ParticleGenerator::m_billboard)
        .field("direction", &mud::ParticleGenerator::m_direction)
        .field("rotation", &mud::ParticleGenerator::m_rotation)
        .field("blend_mode", &mud::ParticleGenerator::m_blend_mode)
        .field("volume", &mud::ParticleGenerator::m_volume)
        .field("rate", &mud::ParticleGenerator::m_rate)
        .field("lifetime", &mud::ParticleGenerator::m_lifetime)
        .field("gravity", &mud::ParticleGenerator::m_gravity)
        .field("speed", &mud::ParticleGenerator::m_speed)
        .field("angle", &mud::ParticleGenerator::m_angle)
        .field("blend", &mud::ParticleGenerator::m_blend)
        .field("colour", &mud::ParticleGenerator::m_colour)
        .field("scale", &mud::ParticleGenerator::m_scale)
        .field("sprite_frame", &mud::ParticleGenerator::m_sprite_frame)
        .field("sprite_name", &mud::ParticleGenerator::m_sprite_name)
        ;
    value_object<mud::PbrMaterialBlock>("PbrMaterialBlock")
        .field("enabled", &mud::PbrMaterialBlock::m_enabled)
        .field("albedo", &mud::PbrMaterialBlock::m_albedo)
        .field("specular", &mud::PbrMaterialBlock::m_specular)
        .field("metallic", &mud::PbrMaterialBlock::m_metallic)
        .field("roughness", &mud::PbrMaterialBlock::m_roughness)
        .field("emissive", &mud::PbrMaterialBlock::m_emissive)
        .field("emissive_energy", &mud::PbrMaterialBlock::m_emissive_energy)
        .field("normal", &mud::PbrMaterialBlock::m_normal)
        .field("rim", &mud::PbrMaterialBlock::m_rim)
        .field("ritint", &mud::PbrMaterialBlock::m_rim_tint)
        .field("clearcoat", &mud::PbrMaterialBlock::m_clearcoat)
        .field("clearcoat_gloss", &mud::PbrMaterialBlock::m_clearcoat_gloss)
        .field("anisotropy", &mud::PbrMaterialBlock::m_anisotropy)
        .field("subsurface", &mud::PbrMaterialBlock::m_subsurface)
        .field("transmission", &mud::PbrMaterialBlock::m_transmission)
        .field("refraction", &mud::PbrMaterialBlock::m_refraction)
        .field("ambient_occlusion", &mud::PbrMaterialBlock::m_ambient_occlusion)
        .field("depth", &mud::PbrMaterialBlock::m_depth)
        .field("deep_parallax", &mud::PbrMaterialBlock::m_deep_parallax)
        .field("diffuse_mode", &mud::PbrMaterialBlock::m_diffuse_mode)
        .field("specular_mode", &mud::PbrMaterialBlock::m_specular_mode)
        ;
    value_object<mud::Radiance>("Radiance")
        .field("energy", &mud::Radiance::m_energy)
        .field("ambient", &mud::Radiance::m_ambient)
        .field("colour", &mud::Radiance::m_colour)
        .field("texture", &mud::Radiance::m_texture)
        ;
    value_object<mud::RenderFrame>("RenderFrame")
        ;
    value_object<mud::RenderQuad>("RenderQuad")
        ;
    value_object<mud::Sun>("Sun")
        .field("azimuth", &mud::Sun::azimuth)
        .field("elevation", &mud::Sun::elevation)
        .field("colour", &mud::Sun::m_colour)
        .field("intensity", &mud::Sun::m_intensity)
        ;
    value_object<mud::UnshadedMaterialBlock>("UnshadedMaterialBlock")
        .field("enabled", &mud::UnshadedMaterialBlock::m_enabled)
        .field("colour", &mud::UnshadedMaterialBlock::m_colour)
        ;
    value_object<mud::ClusteredFrustum>("ClusteredFrustum")
        ;
    value_object<mud::Particles>("Particles")
        .field("node", &mud::Particles::m_node)
        ;
    
    // Classes
    class_<mud::Animated>("Animated")
        .property("playing", &mud::Animated::m_playing)
        .property("queue", &mud::Animated::m_queue)
        .property("active", &mud::Animated::m_active)
        .property("speed_scale", &mud::Animated::m_speed_scale)
        .property("default_blend_time", &mud::Animated::m_default_blend_time)
        .function("start", &mud::Animated::start)
        .function("play", &mud::Animated::play)
        .function("seek", &mud::Animated::seek)
        .function("pause", &mud::Animated::pause)
        .function("stop", &mud::Animated::stop)
        .function("advance", &mud::Animated::advance)
        .function("next_animation", &mud::Animated::next_animation)
        .function("playing", &mud::Animated::playing)
        ;
    class_<mud::Animation>("Animation")
        .property("name", &mud::Animation::m_name)
        .property("length", &mud::Animation::m_length)
        .property("step", &mud::Animation::m_step)
        ;
    class_<mud::AnimationTrack>("AnimationTrack")
        .property("animation", &mud::AnimationTrack::m_animation)
        .property("node", &mud::AnimationTrack::m_node)
        .property("node_name", &mud::AnimationTrack::m_node_name)
        .property("target", &mud::AnimationTrack::m_target)
        .property("value_type", &mud::AnimationTrack::m_value_type)
        .property("length", &mud::AnimationTrack::m_length)
        .property("interpolation", &mud::AnimationTrack::m_interpolation)
        ;
    class_<mud::AssetStore<mud::Material>>("AssetStore<mud::Material>")
        .function("get", &mud::AssetStore<mud::Material>::get)
        .function("create", &mud::AssetStore<mud::Material>::create)
        .function("fetch", &mud::AssetStore<mud::Material>::fetch)
        .function("file_at", &mud::AssetStore<mud::Material>::file_at)
        .function("file", &mud::AssetStore<mud::Material>::file)
        .function("destroy", &mud::AssetStore<mud::Material>::destroy)
        ;
    class_<mud::AssetStore<mud::Model>>("AssetStore<mud::Model>")
        .function("get", &mud::AssetStore<mud::Model>::get)
        .function("create", &mud::AssetStore<mud::Model>::create)
        .function("fetch", &mud::AssetStore<mud::Model>::fetch)
        .function("file_at", &mud::AssetStore<mud::Model>::file_at)
        .function("file", &mud::AssetStore<mud::Model>::file)
        .function("destroy", &mud::AssetStore<mud::Model>::destroy)
        ;
    class_<mud::AssetStore<mud::ParticleGenerator>>("AssetStore<mud::ParticleGenerator>")
        .function("get", &mud::AssetStore<mud::ParticleGenerator>::get)
        .function("create", &mud::AssetStore<mud::ParticleGenerator>::create)
        .function("fetch", &mud::AssetStore<mud::ParticleGenerator>::fetch)
        .function("file_at", &mud::AssetStore<mud::ParticleGenerator>::file_at)
        .function("file", &mud::AssetStore<mud::ParticleGenerator>::file)
        .function("destroy", &mud::AssetStore<mud::ParticleGenerator>::destroy)
        ;
    class_<mud::AssetStore<mud::Prefab>>("AssetStore<mud::Prefab>")
        .function("get", &mud::AssetStore<mud::Prefab>::get)
        .function("create", &mud::AssetStore<mud::Prefab>::create)
        .function("fetch", &mud::AssetStore<mud::Prefab>::fetch)
        .function("file_at", &mud::AssetStore<mud::Prefab>::file_at)
        .function("file", &mud::AssetStore<mud::Prefab>::file)
        .function("destroy", &mud::AssetStore<mud::Prefab>::destroy)
        ;
    class_<mud::AssetStore<mud::Program>>("AssetStore<mud::Program>")
        .function("get", &mud::AssetStore<mud::Program>::get)
        .function("create", &mud::AssetStore<mud::Program>::create)
        .function("fetch", &mud::AssetStore<mud::Program>::fetch)
        .function("file_at", &mud::AssetStore<mud::Program>::file_at)
        .function("file", &mud::AssetStore<mud::Program>::file)
        .function("destroy", &mud::AssetStore<mud::Program>::destroy)
        ;
    class_<mud::AssetStore<mud::Texture>>("AssetStore<mud::Texture>")
        .function("get", &mud::AssetStore<mud::Texture>::get)
        .function("create", &mud::AssetStore<mud::Texture>::create)
        .function("fetch", &mud::AssetStore<mud::Texture>::fetch)
        .function("file_at", &mud::AssetStore<mud::Texture>::file_at)
        .function("file", &mud::AssetStore<mud::Texture>::file)
        .function("destroy", &mud::AssetStore<mud::Texture>::destroy)
        ;
    class_<mud::Camera>("Camera")
        .property("eye", &mud::Camera::m_eye)
        .property("target", &mud::Camera::m_target)
        .property("transform", &mud::Camera::m_transform)
        .property("projection", &mud::Camera::m_projection)
        .property("fov", &mud::Camera::m_fov)
        .property("aspect", &mud::Camera::m_aspect)
        .property("near", &mud::Camera::m_near)
        .property("far", &mud::Camera::m_far)
        .property("orthographic", &mud::Camera::m_orthographic)
        .property("height", &mud::Camera::m_height)
        .property("optimize_ends", &mud::Camera::m_optimize_ends)
        .property("clustered", &mud::Camera::m_clustered)
        .property("lod_offsets", &mud::Camera::m_lod_offsets)
        ;
    class_<mud::Filter>("Filter")
        ;
    class_<mud::FrameBuffer>("FrameBuffer")
        ;
    class_<mud::Frustum>("Frustum")
        .property("fov", &mud::Frustum::m_fov)
        .property("aspect", &mud::Frustum::m_aspect)
        .property("near", &mud::Frustum::m_near)
        .property("far", &mud::Frustum::m_far)
        .property("center", &mud::Frustum::m_center)
        .property("radius", &mud::Frustum::m_radius)
        ;
    class_<mud::GfxBlock>("GfxBlock")
        .property("type", &mud::GfxBlock::m_type)
        .property("index", &mud::GfxBlock::m_index)
        ;
    class_<mud::GfxContext>("GfxContext")
        ;
    class_<mud::GfxSystem>("GfxSystem")
        .property("textures", &mud::GfxSystem::textures, &mud::GfxSystem::setTextures)
        .property("programs", &mud::GfxSystem::programs, &mud::GfxSystem::setPrograms)
        .property("materials", &mud::GfxSystem::materials, &mud::GfxSystem::setMaterials)
        .property("models", &mud::GfxSystem::models, &mud::GfxSystem::setModels)
        .property("particles", &mud::GfxSystem::particles, &mud::GfxSystem::setParticles)
        .property("prefabs", &mud::GfxSystem::prefabs, &mud::GfxSystem::setPrefabs)
        .function("add_resource_path", &mud::GfxSystem::add_resource_path)
        .function("debug_material", &mud::GfxSystem::debug_material)
        .function("fetch_material", &mud::GfxSystem::fetch_material)
        .function("fetch_image256_material", &mud::GfxSystem::fetch_image256_material)
        .function("fetch_symbol", &mud::GfxSystem::fetch_symbol)
        .function("fetch_symbol_material", &mud::GfxSystem::fetch_symbol_material)
        ;
    class_<mud::Gnode>("Gnode")
        ;
    class_<mud::ImmediateDraw>("ImmediateDraw")
        ;
    class_<mud::Item>("Item")
        .property("node", &mud::Item::m_node)
        .property("model", &mud::Item::m_model)
        .property("flags", &mud::Item::m_flags)
        .property("colour", &mud::Item::m_colour)
        .property("material", &mud::Item::m_material)
        .property("visible", &mud::Item::m_visible)
        .property("shadow", &mud::Item::m_shadow)
        .property("rig", &mud::Item::m_rig)
        ;
    class_<mud::Light>("Light")
        .property("node", &mud::Light::m_node)
        .property("type", &mud::Light::m_type)
        .property("visible", &mud::Light::m_visible)
        .property("colour", &mud::Light::m_colour)
        .property("range", &mud::Light::m_range)
        .property("energy", &mud::Light::m_energy)
        .property("specular", &mud::Light::m_specular)
        .property("attenuation", &mud::Light::m_attenuation)
        .property("shadows", &mud::Light::m_shadows)
        .property("shadow_colour", &mud::Light::m_shadow_colour)
        .property("shadow_range", &mud::Light::m_shadow_range)
        .property("layers", &mud::Light::m_layers)
        .property("last_render", &mud::Light::m_last_render)
        .property("last_update", &mud::Light::m_last_update)
        .property("spot_angle", &mud::Light::m_spot_angle)
        .property("spot_attenuation", &mud::Light::m_spot_attenuation)
        .property("shadow_flags", &mud::Light::m_shadow_flags)
        .property("shadow_nusplits", &mud::Light::m_shadow_num_splits)
        .property("shadow_split_distribution", &mud::Light::m_shadow_split_distribution)
        .property("shadow_normal_bias", &mud::Light::m_shadow_normal_bias)
        .property("shadow_bias", &mud::Light::m_shadow_bias)
        ;
    class_<mud::Material>("Material")
        .property("index", &mud::Material::m_index)
        .property("builtin", &mud::Material::m_builtin)
        .property("program", &mud::Material::m_program)
        .property("base_block", &mud::Material::m_base_block)
        .property("unshaded_block", &mud::Material::m_unshaded_block)
        .property("pbr_block", &mud::Material::m_pbr_block)
        .property("fresnel_block", &mud::Material::m_fresnel_block)
        ;
    class_<mud::Mesh>("Mesh")
        .property("name", &mud::Mesh::m_name)
        .property("index", &mud::Mesh::m_index)
        .property("draw_mode", &mud::Mesh::m_draw_mode)
        .property("aabb", &mud::Mesh::m_aabb)
        .property("radius", &mud::Mesh::m_radius)
        .property("origin", &mud::Mesh::m_origin)
        .property("readback", &mud::Mesh::m_readback)
        .property("vertex_format", &mud::Mesh::m_vertex_format)
        .property("qnormals", &mud::Mesh::m_qnormals)
        .property("vertex_count", &mud::Mesh::m_vertex_count)
        .property("index_count", &mud::Mesh::m_index_count)
        .property("index32", &mud::Mesh::m_index32)
        .property("material", &mud::Mesh::m_material)
        ;
    class_<mud::Model>("Model")
        .property("name", &mud::Model::m_name)
        .property("index", &mud::Model::m_index)
        .property("aabb", &mud::Model::m_aabb)
        .property("radius", &mud::Model::m_radius)
        .property("origin", &mud::Model::m_origin)
        ;
    class_<mud::Node3>("Node3")
        .property("scene", &mud::Node3::m_scene)
        .property("index", &mud::Node3::m_index)
        .property("transform", &mud::Node3::m_transform)
        .property("visible", &mud::Node3::m_visible)
        ;
    class_<mud::Prefab>("Prefab")
        .property("name", &mud::Prefab::m_name)
        ;
    class_<mud::Program>("Program")
        .property("name", &mud::Program::name, &mud::Program::setName)
        ;
    class_<mud::Rig>("Rig")
        ;
    class_<mud::Scene>("Scene")
        .property("graph", &mud::Scene::m_graph)
        .property("root_node", &mud::Scene::m_root_node)
        .property("environment", &mud::Scene::m_environment)
        .property("user", &mud::Scene::m_user)
        .function("begin", &mud::Scene::begin)
        ;
    class_<mud::Shot>("Shot")
        ;
    class_<mud::Skeleton>("Skeleton")
        ;
    class_<mud::Skin>("Skin")
        ;
    class_<mud::SymbolIndex>("SymbolIndex")
        ;
    class_<mud::Texture>("Texture")
        .property("width", &mud::Texture::m_width)
        .property("height", &mud::Texture::m_height)
        .property("bits_per_pixel", &mud::Texture::m_bits_per_pixel)
        ;
    class_<mud::Viewport>("Viewport")
        .property("camera", &mud::Viewport::m_camera)
        .property("scene", &mud::Viewport::m_scene)
        .property("index", &mud::Viewport::m_index)
        .property("active", &mud::Viewport::m_active)
        .property("rect", &mud::Viewport::m_rect)
        .property("scissor", &mud::Viewport::m_scissor)
        .property("clear_colour", &mud::Viewport::m_clear_colour)
        .property("shading", &mud::Viewport::m_shading)
        .property("lighting", &mud::Viewport::m_lighting)
        ;
    class_<mud::BlockCopy>("BlockCopy")
        ;
    class_<mud::DrawBlock>("DrawBlock")
        ;
    class_<mud::BlockDepth>("BlockDepth")
        ;
    class_<mud::BlockFilter>("BlockFilter")
        ;
    class_<mud::BlockParticles>("BlockParticles")
        ;
    class_<mud::BlockResolve>("BlockResolve")
        ;
    class_<mud::BlockSky>("BlockSky")
        ;
    class_<mud::RenderTarget>("RenderTarget")
        ;
    
    // Functions
    function("update_item_lights", &mud::gfx::update_item_lights);
    function("update_item_aabb", &mud::gfx::update_item_aabb);
    function("node", &mud::gfx::node);
    function("shape", &mud::gfx::shape);
    function("draw", &mud::gfx::draw);
    function("sprite", &mud::gfx::sprite);
    function("item", &mud::gfx::item);
    function("prefab", &mud::gfx::prefab);
    function("model", &mud::gfx::model);
    function("animated", &mud::gfx::animated);
    function("particles", &mud::gfx::particles);
    function("light", &mud::gfx::light);
    function("sun_light", &mud::gfx::sun_light);
    function("radiance", &mud::gfx::radiance);
    
}
