#include <cpp/preimport.h>

#define __EXCEPTION__
#define _GLIBCXX_CMATH
#define _GLIBCXX_NUMERIC_LIMITS
#define _GLIBCXX_STRING
#define _GLIBCXX_VECTOR
#define _GLIBCXX_MAP
#define _GLIBCXX_TUPLE
#define _GLIBCXX_MEMORY
#define _GLIBCXX_CHRONO
#define _GLIBCXX_TYPE_TRAITS
#define _EXT_TYPE_TRAITS
#define _CPP_TYPE_TRAITS_H
#define _GLIBCXX_SYSTEM_ERROR
#define _GLIBCXX_FUNCTIONAL
#define _MOVE_H
#define _MATH_H
#define _INITIALIZER_LIST
